import '../data/models/product_icon.dart';

/// Product Icons Configuration
/// FluentUI Emoji style icons for products
/// Extended library with 100+ free icons and 60+ premium icons
class ProductIcons {
  // ============================================================================
  // FREE ICONS - Available to all users (Flat/Standard style)
  // ============================================================================

  static const List<ProductIcon> freeIcons = [
    // ==================== FRUITS - Free ====================
    ProductIcon(
      id: 'apple_red',
      name: 'Red Apple',
      nameVi: 'Táo đỏ',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍎',
      displayOrder: 1,
      tags: ['apple', 'táo', 'fruit', 'trái cây'],
    ),
    ProductIcon(
      id: 'apple_green',
      name: 'Green Apple',
      nameVi: 'Táo xanh',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍏',
      displayOrder: 2,
      tags: ['apple', 'táo', 'green', 'xanh'],
    ),
    ProductIcon(
      id: 'banana',
      name: 'Banana',
      nameVi: 'Chuối',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍌',
      displayOrder: 3,
      tags: ['banana', 'chuối'],
    ),
    ProductIcon(
      id: 'orange',
      name: 'Orange',
      nameVi: 'Cam',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍊',
      displayOrder: 4,
      tags: ['orange', 'cam'],
    ),
    ProductIcon(
      id: 'tangerine',
      name: 'Tangerine',
      nameVi: 'Quýt',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍊',
      displayOrder: 5,
      tags: ['tangerine', 'quýt', 'mandarin'],
    ),
    ProductIcon(
      id: 'lemon',
      name: 'Lemon',
      nameVi: 'Chanh',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍋',
      displayOrder: 6,
      tags: ['lemon', 'chanh'],
    ),
    ProductIcon(
      id: 'watermelon',
      name: 'Watermelon',
      nameVi: 'Dưa hấu',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍉',
      displayOrder: 7,
      tags: ['watermelon', 'dưa hấu'],
    ),
    ProductIcon(
      id: 'melon',
      name: 'Melon',
      nameVi: 'Dưa lưới',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍈',
      displayOrder: 8,
      tags: ['melon', 'dưa', 'cantaloupe'],
    ),
    ProductIcon(
      id: 'grapes',
      name: 'Grapes',
      nameVi: 'Nho',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍇',
      displayOrder: 9,
      tags: ['grapes', 'nho'],
    ),
    ProductIcon(
      id: 'strawberry',
      name: 'Strawberry',
      nameVi: 'Dâu tây',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍓',
      displayOrder: 10,
      tags: ['strawberry', 'dâu'],
    ),
    ProductIcon(
      id: 'blueberries',
      name: 'Blueberries',
      nameVi: 'Việt quất',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🫐',
      displayOrder: 11,
      tags: ['blueberry', 'việt quất'],
    ),
    ProductIcon(
      id: 'cherries',
      name: 'Cherries',
      nameVi: 'Cherry',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍒',
      displayOrder: 12,
      tags: ['cherry', 'cherries'],
    ),
    ProductIcon(
      id: 'peach',
      name: 'Peach',
      nameVi: 'Đào',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍑',
      displayOrder: 13,
      tags: ['peach', 'đào'],
    ),
    ProductIcon(
      id: 'pear',
      name: 'Pear',
      nameVi: 'Lê',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍐',
      displayOrder: 14,
      tags: ['pear', 'lê'],
    ),
    ProductIcon(
      id: 'pineapple',
      name: 'Pineapple',
      nameVi: 'Dứa',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍍',
      displayOrder: 15,
      tags: ['pineapple', 'dứa', 'thơm'],
    ),
    ProductIcon(
      id: 'mango',
      name: 'Mango',
      nameVi: 'Xoài',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🥭',
      displayOrder: 16,
      tags: ['mango', 'xoài'],
    ),
    ProductIcon(
      id: 'kiwi',
      name: 'Kiwi',
      nameVi: 'Kiwi',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🥝',
      displayOrder: 17,
      tags: ['kiwi'],
    ),
    ProductIcon(
      id: 'avocado',
      name: 'Avocado',
      nameVi: 'Bơ',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🥑',
      displayOrder: 18,
      tags: ['avocado', 'bơ'],
    ),
    ProductIcon(
      id: 'coconut',
      name: 'Coconut',
      nameVi: 'Dừa',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🥥',
      displayOrder: 19,
      tags: ['coconut', 'dừa'],
    ),
    ProductIcon(
      id: 'papaya',
      name: 'Papaya',
      nameVi: 'Đu đủ',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍈',
      displayOrder: 20,
      tags: ['papaya', 'đu đủ'],
    ),

    // ==================== VEGETABLES - Free ====================
    ProductIcon(
      id: 'tomato',
      name: 'Tomato',
      nameVi: 'Cà chua',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🍅',
      displayOrder: 1,
      tags: ['tomato', 'cà chua'],
    ),
    ProductIcon(
      id: 'carrot',
      name: 'Carrot',
      nameVi: 'Cà rốt',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🥕',
      displayOrder: 2,
      tags: ['carrot', 'cà rốt'],
    ),
    ProductIcon(
      id: 'broccoli',
      name: 'Broccoli',
      nameVi: 'Bông cải xanh',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🥦',
      displayOrder: 3,
      tags: ['broccoli', 'bông cải'],
    ),
    ProductIcon(
      id: 'cauliflower',
      name: 'Cauliflower',
      nameVi: 'Súp lơ trắng',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🥦',
      displayOrder: 4,
      tags: ['cauliflower', 'súp lơ'],
    ),
    ProductIcon(
      id: 'corn',
      name: 'Corn',
      nameVi: 'Ngô',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🌽',
      displayOrder: 5,
      tags: ['corn', 'ngô'],
    ),
    ProductIcon(
      id: 'potato',
      name: 'Potato',
      nameVi: 'Khoai tây',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🥔',
      displayOrder: 6,
      tags: ['potato', 'khoai tây'],
    ),
    ProductIcon(
      id: 'sweet_potato',
      name: 'Sweet Potato',
      nameVi: 'Khoai lang',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🍠',
      displayOrder: 7,
      tags: ['sweet potato', 'khoai lang'],
    ),
    ProductIcon(
      id: 'cucumber',
      name: 'Cucumber',
      nameVi: 'Dưa chuột',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🥒',
      displayOrder: 8,
      tags: ['cucumber', 'dưa chuột'],
    ),
    ProductIcon(
      id: 'lettuce',
      name: 'Lettuce',
      nameVi: 'Rau diếp',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🥬',
      displayOrder: 9,
      tags: ['lettuce', 'salad', 'rau diếp'],
    ),
    ProductIcon(
      id: 'cabbage',
      name: 'Cabbage',
      nameVi: 'Bắp cải',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🥬',
      displayOrder: 10,
      tags: ['cabbage', 'bắp cải'],
    ),
    ProductIcon(
      id: 'bell_pepper',
      name: 'Bell Pepper',
      nameVi: 'Ớt chuông',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🫑',
      displayOrder: 11,
      tags: ['pepper', 'ớt chuông'],
    ),
    ProductIcon(
      id: 'hot_pepper',
      name: 'Hot Pepper',
      nameVi: 'Ớt',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🌶️',
      displayOrder: 12,
      tags: ['pepper', 'chili', 'ớt'],
    ),
    ProductIcon(
      id: 'eggplant',
      name: 'Eggplant',
      nameVi: 'Cà tím',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🍆',
      displayOrder: 13,
      tags: ['eggplant', 'cà tím'],
    ),
    ProductIcon(
      id: 'onion',
      name: 'Onion',
      nameVi: 'Hành tây',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🧅',
      displayOrder: 14,
      tags: ['onion', 'hành tây'],
    ),
    ProductIcon(
      id: 'garlic',
      name: 'Garlic',
      nameVi: 'Tỏi',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🧄',
      displayOrder: 15,
      tags: ['garlic', 'tỏi'],
    ),
    ProductIcon(
      id: 'mushroom',
      name: 'Mushroom',
      nameVi: 'Nấm',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🍄',
      displayOrder: 16,
      tags: ['mushroom', 'nấm'],
    ),
    ProductIcon(
      id: 'pumpkin',
      name: 'Pumpkin',
      nameVi: 'Bí ngô',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🎃',
      displayOrder: 17,
      tags: ['pumpkin', 'bí ngô'],
    ),
    ProductIcon(
      id: 'ginger',
      name: 'Ginger',
      nameVi: 'Gừng',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🫚',
      displayOrder: 18,
      tags: ['ginger', 'gừng'],
    ),

    // ==================== MEAT & SEAFOOD - Free ====================
    ProductIcon(
      id: 'beef',
      name: 'Beef',
      nameVi: 'Thịt bò',
      category: 'meat',
      tier: IconTier.free,
      emoji: '🥩',
      displayOrder: 1,
      tags: ['meat', 'thịt', 'beef', 'bò'],
    ),
    ProductIcon(
      id: 'pork',
      name: 'Pork',
      nameVi: 'Thịt heo',
      category: 'meat',
      tier: IconTier.free,
      emoji: '🥓',
      displayOrder: 2,
      tags: ['pork', 'thịt heo', 'heo'],
    ),
    ProductIcon(
      id: 'chicken',
      name: 'Chicken',
      nameVi: 'Gà',
      category: 'meat',
      tier: IconTier.free,
      emoji: '🍗',
      displayOrder: 3,
      tags: ['chicken', 'gà', 'poultry'],
    ),
    ProductIcon(
      id: 'turkey',
      name: 'Turkey',
      nameVi: 'Gà tây',
      category: 'meat',
      tier: IconTier.free,
      emoji: '🦃',
      displayOrder: 4,
      tags: ['turkey', 'gà tây'],
    ),
    ProductIcon(
      id: 'bacon',
      name: 'Bacon',
      nameVi: 'Thịt xông khói',
      category: 'meat',
      tier: IconTier.free,
      emoji: '🥓',
      displayOrder: 5,
      tags: ['bacon', 'thịt xông khói'],
    ),
    ProductIcon(
      id: 'sausage',
      name: 'Sausage',
      nameVi: 'Xúc xích',
      category: 'meat',
      tier: IconTier.free,
      emoji: '🌭',
      displayOrder: 6,
      tags: ['sausage', 'xúc xích'],
    ),
    ProductIcon(
      id: 'ham',
      name: 'Ham',
      nameVi: 'Giăm bông',
      category: 'meat',
      tier: IconTier.free,
      emoji: '🍖',
      displayOrder: 7,
      tags: ['ham', 'giăm bông'],
    ),
    ProductIcon(
      id: 'fish',
      name: 'Fish',
      nameVi: 'Cá',
      category: 'meat',
      tier: IconTier.free,
      emoji: '🐟',
      displayOrder: 8,
      tags: ['fish', 'cá', 'seafood'],
    ),
    ProductIcon(
      id: 'shrimp',
      name: 'Shrimp',
      nameVi: 'Tôm',
      category: 'meat',
      tier: IconTier.free,
      emoji: '🦐',
      displayOrder: 9,
      tags: ['shrimp', 'tôm', 'seafood'],
    ),
    ProductIcon(
      id: 'crab',
      name: 'Crab',
      nameVi: 'Cua',
      category: 'meat',
      tier: IconTier.free,
      emoji: '🦀',
      displayOrder: 10,
      tags: ['crab', 'cua', 'seafood'],
    ),
    ProductIcon(
      id: 'lobster',
      name: 'Lobster',
      nameVi: 'Tôm hùm',
      category: 'meat',
      tier: IconTier.free,
      emoji: '🦞',
      displayOrder: 11,
      tags: ['lobster', 'tôm hùm', 'seafood'],
    ),
    ProductIcon(
      id: 'squid',
      name: 'Squid',
      nameVi: 'Mực',
      category: 'meat',
      tier: IconTier.free,
      emoji: '🦑',
      displayOrder: 12,
      tags: ['squid', 'mực', 'seafood'],
    ),
    ProductIcon(
      id: 'oyster',
      name: 'Oyster',
      nameVi: 'Hàu',
      category: 'meat',
      tier: IconTier.free,
      emoji: '🦪',
      displayOrder: 13,
      tags: ['oyster', 'hàu', 'seafood'],
    ),

    // ==================== EGGS - Free ====================
    ProductIcon(
      id: 'egg',
      name: 'Egg',
      nameVi: 'Trứng',
      category: 'eggs',
      tier: IconTier.free,
      emoji: '🥚',
      displayOrder: 1,
      tags: ['egg', 'trứng'],
    ),
    ProductIcon(
      id: 'fried_egg',
      name: 'Fried Egg',
      nameVi: 'Trứng chiên',
      category: 'eggs',
      tier: IconTier.free,
      emoji: '🍳',
      displayOrder: 2,
      tags: ['egg', 'trứng chiên', 'fried'],
    ),

    // ==================== DAIRY - Free ====================
    ProductIcon(
      id: 'milk',
      name: 'Milk',
      nameVi: 'Sữa',
      category: 'dairy',
      tier: IconTier.free,
      emoji: '🥛',
      displayOrder: 1,
      tags: ['milk', 'sữa'],
    ),
    ProductIcon(
      id: 'cheese',
      name: 'Cheese',
      nameVi: 'Phô mai',
      category: 'dairy',
      tier: IconTier.free,
      emoji: '🧀',
      displayOrder: 2,
      tags: ['cheese', 'phô mai'],
    ),
    ProductIcon(
      id: 'butter',
      name: 'Butter',
      nameVi: 'Bơ',
      category: 'dairy',
      tier: IconTier.free,
      emoji: '🧈',
      displayOrder: 3,
      tags: ['butter', 'bơ'],
    ),
    ProductIcon(
      id: 'yogurt',
      name: 'Yogurt',
      nameVi: 'Sữa chua',
      category: 'dairy',
      tier: IconTier.free,
      emoji: '🥛',
      displayOrder: 4,
      tags: ['yogurt', 'sữa chua'],
    ),
    ProductIcon(
      id: 'ice_cream',
      name: 'Ice Cream',
      nameVi: 'Kem',
      category: 'dairy',
      tier: IconTier.free,
      emoji: '🍦',
      displayOrder: 5,
      tags: ['ice cream', 'kem'],
    ),
    ProductIcon(
      id: 'cream',
      name: 'Cream',
      nameVi: 'Kem sữa',
      category: 'dairy',
      tier: IconTier.free,
      emoji: '🥛',
      displayOrder: 6,
      tags: ['cream', 'kem sữa'],
    ),

    // ==================== DRY FOOD - Free ====================
    ProductIcon(
      id: 'bread',
      name: 'Bread',
      nameVi: 'Bánh mì',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🍞',
      displayOrder: 1,
      tags: ['bread', 'bánh mì'],
    ),
    ProductIcon(
      id: 'baguette',
      name: 'Baguette',
      nameVi: 'Bánh mì que',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🥖',
      displayOrder: 2,
      tags: ['bread', 'bánh mì', 'baguette'],
    ),
    ProductIcon(
      id: 'croissant',
      name: 'Croissant',
      nameVi: 'Bánh sừng bò',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🥐',
      displayOrder: 3,
      tags: ['croissant', 'bánh'],
    ),
    ProductIcon(
      id: 'bagel',
      name: 'Bagel',
      nameVi: 'Bánh vòng',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🥯',
      displayOrder: 4,
      tags: ['bagel', 'bánh'],
    ),
    ProductIcon(
      id: 'pretzel',
      name: 'Pretzel',
      nameVi: 'Bánh quy xoắn',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🥨',
      displayOrder: 5,
      tags: ['pretzel', 'bánh'],
    ),
    ProductIcon(
      id: 'rice',
      name: 'Rice',
      nameVi: 'Cơm',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🍚',
      displayOrder: 6,
      tags: ['rice', 'cơm', 'gạo'],
    ),
    ProductIcon(
      id: 'rice_ball',
      name: 'Rice Ball',
      nameVi: 'Cơm nắm',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🍙',
      displayOrder: 7,
      tags: ['rice', 'cơm'],
    ),
    ProductIcon(
      id: 'rice_cracker',
      name: 'Rice Cracker',
      nameVi: 'Bánh gạo',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🍘',
      displayOrder: 8,
      tags: ['rice', 'cracker', 'bánh'],
    ),
    ProductIcon(
      id: 'noodles',
      name: 'Noodles',
      nameVi: 'Mì',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🍜',
      displayOrder: 9,
      tags: ['noodles', 'mì', 'noodle'],
    ),
    ProductIcon(
      id: 'spaghetti',
      name: 'Spaghetti',
      nameVi: 'Mì Ý',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🍝',
      displayOrder: 10,
      tags: ['pasta', 'spaghetti', 'mì'],
    ),
    ProductIcon(
      id: 'cookie',
      name: 'Cookie',
      nameVi: 'Bánh quy',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🍪',
      displayOrder: 11,
      tags: ['cookie', 'bánh quy'],
    ),
    ProductIcon(
      id: 'cracker',
      name: 'Cracker',
      nameVi: 'Bánh cracker',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🥨',
      displayOrder: 12,
      tags: ['cracker', 'bánh'],
    ),
    ProductIcon(
      id: 'peanuts',
      name: 'Peanuts',
      nameVi: 'Đậu phộng',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🥜',
      displayOrder: 13,
      tags: ['peanuts', 'đậu phộng', 'nuts'],
    ),
    ProductIcon(
      id: 'chestnut',
      name: 'Chestnut',
      nameVi: 'Hạt dẻ',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🌰',
      displayOrder: 14,
      tags: ['chestnut', 'hạt dẻ', 'nuts'],
    ),
    ProductIcon(
      id: 'beans',
      name: 'Beans',
      nameVi: 'Đậu',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🫘',
      displayOrder: 15,
      tags: ['beans', 'đậu'],
    ),
    ProductIcon(
      id: 'cereal',
      name: 'Cereal',
      nameVi: 'Ngũ cốc',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🥣',
      displayOrder: 16,
      tags: ['cereal', 'ngũ cốc'],
    ),
    ProductIcon(
      id: 'popcorn',
      name: 'Popcorn',
      nameVi: 'Bắp rang',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🍿',
      displayOrder: 17,
      tags: ['popcorn', 'bắp rang'],
    ),
    ProductIcon(
      id: 'chocolate',
      name: 'Chocolate',
      nameVi: 'Socola',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🍫',
      displayOrder: 18,
      tags: ['chocolate', 'socola'],
    ),
    ProductIcon(
      id: 'candy',
      name: 'Candy',
      nameVi: 'Kẹo',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🍬',
      displayOrder: 19,
      tags: ['candy', 'kẹo'],
    ),
    ProductIcon(
      id: 'honey',
      name: 'Honey',
      nameVi: 'Mật ong',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🍯',
      displayOrder: 20,
      tags: ['honey', 'mật ong'],
    ),
  ];

  // ============================================================================
  // PREMIUM ICONS - Require premium subscription (3D/Premium style)
  // ============================================================================

  static const List<ProductIcon> premiumIcons = [
    // ==================== FRUITS - Premium (3D style with effects) ====================
    ProductIcon(
      id: 'apple_gold_3d',
      name: '✨ Golden Apple 3D',
      nameVi: '✨ Táo vàng 3D',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '✨🍎✨',
      isAnimated: true,
      displayOrder: 100,
      tags: ['apple', 'táo', 'premium', 'gold', '3d'],
    ),
    ProductIcon(
      id: 'apple_diamond',
      name: '💎 Diamond Apple',
      nameVi: '💎 Táo kim cương',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '💎🍎💎',
      isAnimated: true,
      displayOrder: 101,
      tags: ['apple', 'táo', 'premium', 'diamond', '3d'],
    ),
    ProductIcon(
      id: 'banana_gold_3d',
      name: '🌟 Golden Banana 3D',
      nameVi: '🌟 Chuối vàng 3D',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '🌟🍌🌟',
      isAnimated: true,
      displayOrder: 102,
      tags: ['banana', 'chuối', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'orange_sparkle_3d',
      name: '✨ Sparkling Orange 3D',
      nameVi: '✨ Cam lấp lánh 3D',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '✨🍊✨',
      isAnimated: true,
      displayOrder: 103,
      tags: ['orange', 'cam', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'strawberry_diamond_3d',
      name: '💎 Diamond Strawberry 3D',
      nameVi: '💎 Dâu kim cương 3D',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '💎🍓💎',
      isAnimated: true,
      displayOrder: 104,
      tags: ['strawberry', 'dâu', 'premium', 'diamond', '3d'],
    ),
    ProductIcon(
      id: 'watermelon_star_3d',
      name: '⭐ Star Watermelon 3D',
      nameVi: '⭐ Dưa hấu ngôi sao 3D',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '⭐🍉⭐',
      isAnimated: true,
      displayOrder: 105,
      tags: ['watermelon', 'dưa hấu', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'grapes_royal_3d',
      name: '👑 Royal Grapes 3D',
      nameVi: '👑 Nho hoàng gia 3D',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '👑🍇👑',
      isAnimated: true,
      displayOrder: 106,
      tags: ['grapes', 'nho', 'premium', 'royal', '3d'],
    ),
    ProductIcon(
      id: 'mango_gold_3d',
      name: '✨ Golden Mango 3D',
      nameVi: '✨ Xoài vàng 3D',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '✨🥭✨',
      isAnimated: true,
      displayOrder: 107,
      tags: ['mango', 'xoài', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'peach_premium_3d',
      name: '🌟 Premium Peach 3D',
      nameVi: '🌟 Đào cao cấp 3D',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '🌟🍑🌟',
      isAnimated: true,
      displayOrder: 108,
      tags: ['peach', 'đào', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'pineapple_gold_3d',
      name: '👑 Golden Pineapple 3D',
      nameVi: '👑 Dứa vàng 3D',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '👑🍍👑',
      isAnimated: true,
      displayOrder: 109,
      tags: ['pineapple', 'dứa', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'kiwi_sparkle_3d',
      name: '💫 Sparkling Kiwi 3D',
      nameVi: '💫 Kiwi lấp lánh 3D',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '💫🥝💫',
      isAnimated: true,
      displayOrder: 110,
      tags: ['kiwi', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'avocado_premium_3d',
      name: '✨ Premium Avocado 3D',
      nameVi: '✨ Bơ cao cấp 3D',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '✨🥑✨',
      isAnimated: true,
      displayOrder: 111,
      tags: ['avocado', 'bơ', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'coconut_gold_3d',
      name: '🌟 Golden Coconut 3D',
      nameVi: '🌟 Dừa vàng 3D',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '🌟🥥🌟',
      isAnimated: true,
      displayOrder: 112,
      tags: ['coconut', 'dừa', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'cherry_diamond_3d',
      name: '💎 Diamond Cherry 3D',
      nameVi: '💎 Cherry kim cương 3D',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '💎🍒💎',
      isAnimated: true,
      displayOrder: 113,
      tags: ['cherry', 'premium', 'diamond', '3d'],
    ),
    ProductIcon(
      id: 'blueberry_star_3d',
      name: '⭐ Star Blueberry 3D',
      nameVi: '⭐ Việt quất ngôi sao 3D',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '⭐🫐⭐',
      isAnimated: true,
      displayOrder: 114,
      tags: ['blueberry', 'việt quất', 'premium', '3d'],
    ),

    // ==================== VEGETABLES - Premium (3D style) ====================
    ProductIcon(
      id: 'tomato_gold_3d',
      name: '✨ Golden Tomato 3D',
      nameVi: '✨ Cà chua vàng 3D',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '✨🍅✨',
      isAnimated: true,
      displayOrder: 100,
      tags: ['tomato', 'cà chua', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'carrot_diamond_3d',
      name: '💎 Diamond Carrot 3D',
      nameVi: '💎 Cà rốt kim cương 3D',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '💎🥕💎',
      isAnimated: true,
      displayOrder: 101,
      tags: ['carrot', 'cà rốt', 'premium', 'diamond', '3d'],
    ),
    ProductIcon(
      id: 'broccoli_star_3d',
      name: '⭐ Star Broccoli 3D',
      nameVi: '⭐ Bông cải ngôi sao 3D',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '⭐🥦⭐',
      isAnimated: true,
      displayOrder: 102,
      tags: ['broccoli', 'bông cải', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'corn_gold_3d',
      name: '🌟 Golden Corn 3D',
      nameVi: '🌟 Ngô vàng 3D',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '🌟🌽🌟',
      isAnimated: true,
      displayOrder: 103,
      tags: ['corn', 'ngô', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'potato_premium_3d',
      name: '✨ Premium Potato 3D',
      nameVi: '✨ Khoai tây cao cấp 3D',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '✨🥔✨',
      isAnimated: true,
      displayOrder: 104,
      tags: ['potato', 'khoai tây', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'cucumber_sparkle_3d',
      name: '💫 Sparkling Cucumber 3D',
      nameVi: '💫 Dưa chuột lấp lánh 3D',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '💫🥒💫',
      isAnimated: true,
      displayOrder: 105,
      tags: ['cucumber', 'dưa chuột', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'pepper_royal_3d',
      name: '👑 Royal Pepper 3D',
      nameVi: '👑 Ớt chuông hoàng gia 3D',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '👑🫑👑',
      isAnimated: true,
      displayOrder: 106,
      tags: ['pepper', 'ớt chuông', 'premium', 'royal', '3d'],
    ),
    ProductIcon(
      id: 'eggplant_premium_3d',
      name: '✨ Premium Eggplant 3D',
      nameVi: '✨ Cà tím cao cấp 3D',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '✨🍆✨',
      isAnimated: true,
      displayOrder: 107,
      tags: ['eggplant', 'cà tím', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'mushroom_gold_3d',
      name: '🌟 Golden Mushroom 3D',
      nameVi: '🌟 Nấm vàng 3D',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '🌟🍄🌟',
      isAnimated: true,
      displayOrder: 108,
      tags: ['mushroom', 'nấm', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'lettuce_premium_3d',
      name: '💎 Premium Lettuce 3D',
      nameVi: '💎 Rau diếp cao cấp 3D',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '💎🥬💎',
      isAnimated: true,
      displayOrder: 109,
      tags: ['lettuce', 'rau diếp', 'premium', '3d'],
    ),

    // ==================== MEAT & SEAFOOD - Premium (3D style) ====================
    ProductIcon(
      id: 'wagyu_beef_3d',
      name: '👑 Wagyu Beef 3D',
      nameVi: '👑 Thịt bò Wagyu 3D',
      category: 'meat',
      tier: IconTier.premium,
      emoji: '👑🥩👑',
      isAnimated: true,
      displayOrder: 100,
      tags: ['meat', 'thịt', 'wagyu', 'premium', 'beef', '3d'],
    ),
    ProductIcon(
      id: 'premium_beef_3d',
      name: '💎 Premium Beef 3D',
      nameVi: '💎 Thịt bò cao cấp 3D',
      category: 'meat',
      tier: IconTier.premium,
      emoji: '💎🥩💎',
      isAnimated: true,
      displayOrder: 101,
      tags: ['meat', 'thịt', 'premium', 'beef', '3d'],
    ),
    ProductIcon(
      id: 'premium_chicken_3d',
      name: '✨ Premium Chicken 3D',
      nameVi: '✨ Gà cao cấp 3D',
      category: 'meat',
      tier: IconTier.premium,
      emoji: '✨🍗✨',
      isAnimated: true,
      displayOrder: 102,
      tags: ['chicken', 'gà', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'royal_chicken_3d',
      name: '👑 Royal Chicken 3D',
      nameVi: '👑 Gà hoàng gia 3D',
      category: 'meat',
      tier: IconTier.premium,
      emoji: '👑🍗👑',
      isAnimated: true,
      displayOrder: 103,
      tags: ['chicken', 'gà', 'premium', 'royal', '3d'],
    ),
    ProductIcon(
      id: 'premium_fish_3d',
      name: '🌟 Premium Fish 3D',
      nameVi: '🌟 Cá cao cấp 3D',
      category: 'meat',
      tier: IconTier.premium,
      emoji: '🌟🐟🌟',
      isAnimated: true,
      displayOrder: 104,
      tags: ['fish', 'cá', 'premium', 'seafood', '3d'],
    ),
    ProductIcon(
      id: 'premium_shrimp_3d',
      name: '💎 Premium Shrimp 3D',
      nameVi: '💎 Tôm cao cấp 3D',
      category: 'meat',
      tier: IconTier.premium,
      emoji: '💎🦐💎',
      isAnimated: true,
      displayOrder: 105,
      tags: ['shrimp', 'tôm', 'premium', 'seafood', '3d'],
    ),
    ProductIcon(
      id: 'royal_lobster_3d',
      name: '👑 Royal Lobster 3D',
      nameVi: '👑 Tôm hùm hoàng gia 3D',
      category: 'meat',
      tier: IconTier.premium,
      emoji: '👑🦞👑',
      isAnimated: true,
      displayOrder: 106,
      tags: ['lobster', 'tôm hùm', 'premium', 'royal', 'seafood', '3d'],
    ),
    ProductIcon(
      id: 'premium_crab_3d',
      name: '✨ Premium Crab 3D',
      nameVi: '✨ Cua cao cấp 3D',
      category: 'meat',
      tier: IconTier.premium,
      emoji: '✨🦀✨',
      isAnimated: true,
      displayOrder: 107,
      tags: ['crab', 'cua', 'premium', 'seafood', '3d'],
    ),
    ProductIcon(
      id: 'premium_oyster_3d',
      name: '💎 Premium Oyster 3D',
      nameVi: '💎 Hàu cao cấp 3D',
      category: 'meat',
      tier: IconTier.premium,
      emoji: '💎🦪💎',
      isAnimated: true,
      displayOrder: 108,
      tags: ['oyster', 'hàu', 'premium', 'seafood', '3d'],
    ),

    // ==================== EGGS - Premium (3D style) ====================
    ProductIcon(
      id: 'golden_egg_3d',
      name: '✨ Golden Egg 3D',
      nameVi: '✨ Trứng vàng 3D',
      category: 'eggs',
      tier: IconTier.premium,
      emoji: '✨🥚✨',
      isAnimated: true,
      displayOrder: 100,
      tags: ['egg', 'trứng', 'premium', 'gold', '3d'],
    ),
    ProductIcon(
      id: 'diamond_egg_3d',
      name: '💎 Diamond Egg 3D',
      nameVi: '💎 Trứng kim cương 3D',
      category: 'eggs',
      tier: IconTier.premium,
      emoji: '💎🥚💎',
      isAnimated: true,
      displayOrder: 101,
      tags: ['egg', 'trứng', 'premium', 'diamond', '3d'],
    ),
    ProductIcon(
      id: 'premium_fried_egg_3d',
      name: '🌟 Premium Fried Egg 3D',
      nameVi: '🌟 Trứng chiên cao cấp 3D',
      category: 'eggs',
      tier: IconTier.premium,
      emoji: '🌟🍳🌟',
      isAnimated: true,
      displayOrder: 102,
      tags: ['egg', 'trứng chiên', 'premium', '3d'],
    ),

    // ==================== DAIRY - Premium (3D style) ====================
    ProductIcon(
      id: 'organic_milk_3d',
      name: '🌿 Organic Milk 3D',
      nameVi: '🌿 Sữa hữu cơ 3D',
      category: 'dairy',
      tier: IconTier.premium,
      emoji: '🌿🥛🌿',
      isAnimated: true,
      displayOrder: 100,
      tags: ['milk', 'sữa', 'organic', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'golden_milk_3d',
      name: '✨ Golden Milk 3D',
      nameVi: '✨ Sữa vàng 3D',
      category: 'dairy',
      tier: IconTier.premium,
      emoji: '✨🥛✨',
      isAnimated: true,
      displayOrder: 101,
      tags: ['milk', 'sữa', 'premium', 'gold', '3d'],
    ),
    ProductIcon(
      id: 'premium_cheese_3d',
      name: '👑 Premium Cheese 3D',
      nameVi: '👑 Phô mai cao cấp 3D',
      category: 'dairy',
      tier: IconTier.premium,
      emoji: '👑🧀👑',
      isAnimated: true,
      displayOrder: 102,
      tags: ['cheese', 'phô mai', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'golden_cheese_3d',
      name: '✨ Golden Cheese 3D',
      nameVi: '✨ Phô mai vàng 3D',
      category: 'dairy',
      tier: IconTier.premium,
      emoji: '✨🧀✨',
      isAnimated: true,
      displayOrder: 103,
      tags: ['cheese', 'phô mai', 'premium', 'gold', '3d'],
    ),
    ProductIcon(
      id: 'premium_butter_3d',
      name: '🌟 Premium Butter 3D',
      nameVi: '🌟 Bơ cao cấp 3D',
      category: 'dairy',
      tier: IconTier.premium,
      emoji: '🌟🧈🌟',
      isAnimated: true,
      displayOrder: 104,
      tags: ['butter', 'bơ', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'premium_ice_cream_3d',
      name: '✨ Premium Ice Cream 3D',
      nameVi: '✨ Kem cao cấp 3D',
      category: 'dairy',
      tier: IconTier.premium,
      emoji: '✨🍦✨',
      isAnimated: true,
      displayOrder: 105,
      tags: ['ice cream', 'kem', 'premium', '3d'],
    ),

    // ==================== DRY FOOD - Premium (3D style) ====================
    ProductIcon(
      id: 'premium_bread_3d',
      name: '✨ Premium Bread 3D',
      nameVi: '✨ Bánh mì cao cấp 3D',
      category: 'dry_food',
      tier: IconTier.premium,
      emoji: '✨🍞✨',
      isAnimated: true,
      displayOrder: 100,
      tags: ['bread', 'bánh mì', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'golden_baguette_3d',
      name: '🌟 Golden Baguette 3D',
      nameVi: '🌟 Bánh mì que vàng 3D',
      category: 'dry_food',
      tier: IconTier.premium,
      emoji: '🌟🥖🌟',
      isAnimated: true,
      displayOrder: 101,
      tags: ['bread', 'bánh mì', 'baguette', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'premium_rice_3d',
      name: '👑 Premium Rice 3D',
      nameVi: '👑 Gạo cao cấp 3D',
      category: 'dry_food',
      tier: IconTier.premium,
      emoji: '👑🍚👑',
      isAnimated: true,
      displayOrder: 102,
      tags: ['rice', 'cơm', 'gạo', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'premium_noodles_3d',
      name: '✨ Premium Noodles 3D',
      nameVi: '✨ Mì cao cấp 3D',
      category: 'dry_food',
      tier: IconTier.premium,
      emoji: '✨🍜✨',
      isAnimated: true,
      displayOrder: 103,
      tags: ['noodles', 'mì', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'premium_chocolate_3d',
      name: '💎 Premium Chocolate 3D',
      nameVi: '💎 Socola cao cấp 3D',
      category: 'dry_food',
      tier: IconTier.premium,
      emoji: '💎🍫💎',
      isAnimated: true,
      displayOrder: 104,
      tags: ['chocolate', 'socola', 'premium', '3d'],
    ),
    ProductIcon(
      id: 'golden_honey_3d',
      name: '✨ Golden Honey 3D',
      nameVi: '✨ Mật ong vàng 3D',
      category: 'dry_food',
      tier: IconTier.premium,
      emoji: '✨🍯✨',
      isAnimated: true,
      displayOrder: 105,
      tags: ['honey', 'mật ong', 'premium', 'gold', '3d'],
    ),
    ProductIcon(
      id: 'premium_cookie_3d',
      name: '🌟 Premium Cookie 3D',
      nameVi: '🌟 Bánh quy cao cấp 3D',
      category: 'dry_food',
      tier: IconTier.premium,
      emoji: '🌟🍪🌟',
      isAnimated: true,
      displayOrder: 106,
      tags: ['cookie', 'bánh quy', 'premium', '3d'],
    ),
  ];

  // ============================================================================
  // HELPER METHODS
  // ============================================================================

  /// Get all icons (free + premium)
  static List<ProductIcon> getAllIcons() {
    return [...freeIcons, ...premiumIcons];
  }

  /// Get icons by category
  static List<ProductIcon> getIconsByCategory(String category) {
    final allIcons = getAllIcons();
    return allIcons
        .where((icon) => icon.category == category)
        .toList()
      ..sort((a, b) => a.displayOrder.compareTo(b.displayOrder));
  }

  /// Get free icons by category
  static List<ProductIcon> getFreeIconsByCategory(String category) {
    return freeIcons
        .where((icon) => icon.category == category)
        .toList()
      ..sort((a, b) => a.displayOrder.compareTo(b.displayOrder));
  }

  /// Get premium icons by category
  static List<ProductIcon> getPremiumIconsByCategory(String category) {
    return premiumIcons
        .where((icon) => icon.category == category)
        .toList()
      ..sort((a, b) => a.displayOrder.compareTo(b.displayOrder));
  }

  /// Get icon by ID
  static ProductIcon? getIconById(String? id) {
    if (id == null) return null;
    try {
      return getAllIcons().firstWhere((icon) => icon.id == id);
    } catch (e) {
      return null;
    }
  }

  /// Search icons
  static List<ProductIcon> searchIcons(String query, String category, {bool isVietnamese = false}) {
    if (query.isEmpty) {
      return getIconsByCategory(category);
    }

    return getAllIcons()
        .where((icon) =>
            icon.category == category &&
            icon.matchesSearch(query, isVietnamese: isVietnamese))
        .toList()
      ..sort((a, b) => a.displayOrder.compareTo(b.displayOrder));
  }

  /// Get total count of free icons
  static int get freeIconCount => freeIcons.length;

  /// Get total count of premium icons
  static int get premiumIconCount => premiumIcons.length;

  /// Get statistics by category
  static Map<String, int> getCategoryStats() {
    final stats = <String, int>{};
    for (final icon in getAllIcons()) {
      stats[icon.category] = (stats[icon.category] ?? 0) + 1;
    }
    return stats;
  }

  /// Get premium stats by category
  static Map<String, int> getPremiumCategoryStats() {
    final stats = <String, int>{};
    for (final icon in premiumIcons) {
      stats[icon.category] = (stats[icon.category] ?? 0) + 1;
    }
    return stats;
  }
}
