import '../data/models/product_icon.dart';

/// Product Icons Configuration
/// Auto-generated icon library
class ProductIcons {
  // ============================================================================
  // FREE ICONS - Available to all users (Flat/SVG style)
  // ============================================================================

  static const List<ProductIcon> freeIcons = [
    ProductIcon(
      id: 'apple_green',
      name: 'Apple Green',
      nameVi: 'Táo xanh',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍎',
      assetPath: 'assets/product_icons/flat/apple_green.svg',
      displayOrder: 1,
      tags: ['apple green', 'táo xanh'],
    ),
    ProductIcon(
      id: 'apple_red',
      name: 'Apple Red',
      nameVi: 'Táo đỏ',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍎',
      assetPath: 'assets/product_icons/flat/apple_red.svg',
      displayOrder: 2,
      tags: ['apple red', 'táo đỏ'],
    ),
    ProductIcon(
      id: 'avocado',
      name: 'Avocado',
      nameVi: 'Avocado',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/avocado.svg',
      displayOrder: 3,
      tags: ['avocado', 'avocado'],
    ),
    ProductIcon(
      id: 'bacon',
      name: 'Bacon',
      nameVi: 'Thịt xông khói',
      category: 'meat',
      tier: IconTier.free,
      emoji: '🥓',
      assetPath: 'assets/product_icons/flat/bacon.svg',
      displayOrder: 4,
      tags: ['bacon', 'thịt xông khói'],
    ),
    ProductIcon(
      id: 'bagel',
      name: 'Bagel',
      nameVi: 'Bagel',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/bagel.svg',
      displayOrder: 5,
      tags: ['bagel', 'bagel'],
    ),
    ProductIcon(
      id: 'baguette',
      name: 'Baguette',
      nameVi: 'Baguette',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/baguette.svg',
      displayOrder: 6,
      tags: ['baguette', 'baguette'],
    ),
    ProductIcon(
      id: 'banana',
      name: 'Banana',
      nameVi: 'Chuối',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍌',
      assetPath: 'assets/product_icons/flat/banana.svg',
      displayOrder: 7,
      tags: ['banana', 'chuối'],
    ),
    ProductIcon(
      id: 'beans',
      name: 'Beans',
      nameVi: 'Đậu',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/beans.svg',
      displayOrder: 8,
      tags: ['beans', 'đậu'],
    ),
    ProductIcon(
      id: 'beef',
      name: 'Beef',
      nameVi: 'Thịt bò',
      category: 'meat',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/beef.svg',
      displayOrder: 9,
      tags: ['beef', 'thịt bò'],
    ),
    ProductIcon(
      id: 'bell_pepper',
      name: 'Bell Pepper',
      nameVi: 'Ớt chuông',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/bell_pepper.svg',
      displayOrder: 10,
      tags: ['bell pepper', 'ớt chuông'],
    ),
    ProductIcon(
      id: 'blueberries',
      name: 'Blueberries',
      nameVi: 'Việt quất',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/blueberries.svg',
      displayOrder: 11,
      tags: ['blueberries', 'việt quất'],
    ),
    ProductIcon(
      id: 'bottle',
      name: 'Bottle',
      nameVi: 'Bottle',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/bottle.svg',
      displayOrder: 12,
      tags: ['bottle', 'bottle'],
    ),
    ProductIcon(
      id: 'bread',
      name: 'Bread',
      nameVi: 'Bánh mì',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🍞',
      assetPath: 'assets/product_icons/flat/bread.svg',
      displayOrder: 13,
      tags: ['bread', 'bánh mì'],
    ),
    ProductIcon(
      id: 'broccoli',
      name: 'Broccoli',
      nameVi: 'Bông cải xanh',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🥦',
      assetPath: 'assets/product_icons/flat/broccoli.svg',
      displayOrder: 14,
      tags: ['broccoli', 'bông cải xanh'],
    ),
    ProductIcon(
      id: 'butter',
      name: 'Butter',
      nameVi: 'Bơ',
      category: 'dairy',
      tier: IconTier.free,
      emoji: '🧈',
      assetPath: 'assets/product_icons/flat/butter.svg',
      displayOrder: 15,
      tags: ['butter', 'bơ'],
    ),
    ProductIcon(
      id: 'cabbage',
      name: 'Cabbage',
      nameVi: 'Bắp cải',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/cabbage.svg',
      displayOrder: 16,
      tags: ['cabbage', 'bắp cải'],
    ),
    ProductIcon(
      id: 'candy',
      name: 'Candy',
      nameVi: 'Candy',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/candy.svg',
      displayOrder: 17,
      tags: ['candy', 'candy'],
    ),
    ProductIcon(
      id: 'carrot',
      name: 'Carrot',
      nameVi: 'Cà rốt',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🥕',
      assetPath: 'assets/product_icons/flat/carrot.svg',
      displayOrder: 18,
      tags: ['carrot', 'cà rốt'],
    ),
    ProductIcon(
      id: 'cauliflower',
      name: 'Cauliflower',
      nameVi: 'Bông cải trắng',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/cauliflower.svg',
      displayOrder: 19,
      tags: ['cauliflower', 'bông cải trắng'],
    ),
    ProductIcon(
      id: 'cereal',
      name: 'Cereal',
      nameVi: 'Ngũ cốc',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/cereal.svg',
      displayOrder: 20,
      tags: ['cereal', 'ngũ cốc'],
    ),
    ProductIcon(
      id: 'cheese',
      name: 'Cheese',
      nameVi: 'Phô mai',
      category: 'dairy',
      tier: IconTier.free,
      emoji: '🧀',
      assetPath: 'assets/product_icons/flat/cheese.svg',
      displayOrder: 21,
      tags: ['cheese', 'phô mai'],
    ),
    ProductIcon(
      id: 'cherries',
      name: 'Cherries',
      nameVi: 'Cherry',
      category: 'other',
      tier: IconTier.free,
      emoji: '🍒',
      assetPath: 'assets/product_icons/flat/cherries.svg',
      displayOrder: 22,
      tags: ['cherries', 'cherry'],
    ),
    ProductIcon(
      id: 'chestnut',
      name: 'Chestnut',
      nameVi: 'Chestnut',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/chestnut.svg',
      displayOrder: 23,
      tags: ['chestnut', 'chestnut'],
    ),
    ProductIcon(
      id: 'chicken',
      name: 'Chicken',
      nameVi: 'Thịt gà',
      category: 'meat',
      tier: IconTier.free,
      emoji: '🍗',
      assetPath: 'assets/product_icons/flat/chicken.svg',
      displayOrder: 24,
      tags: ['chicken', 'thịt gà'],
    ),
    ProductIcon(
      id: 'chocolate',
      name: 'Chocolate',
      nameVi: 'Chocolate',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/chocolate.svg',
      displayOrder: 25,
      tags: ['chocolate', 'chocolate'],
    ),
    ProductIcon(
      id: 'coconut',
      name: 'Coconut',
      nameVi: 'Coconut',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/coconut.svg',
      displayOrder: 26,
      tags: ['coconut', 'coconut'],
    ),
    ProductIcon(
      id: 'cookie',
      name: 'Cookie',
      nameVi: 'Cookie',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/cookie.svg',
      displayOrder: 27,
      tags: ['cookie', 'cookie'],
    ),
    ProductIcon(
      id: 'corn',
      name: 'Corn',
      nameVi: 'Ngô',
      category: 'other',
      tier: IconTier.free,
      emoji: '🌽',
      assetPath: 'assets/product_icons/flat/corn.svg',
      displayOrder: 28,
      tags: ['corn', 'ngô'],
    ),
    ProductIcon(
      id: 'crab',
      name: 'Crab',
      nameVi: 'Cua',
      category: 'other',
      tier: IconTier.free,
      emoji: '🦀',
      assetPath: 'assets/product_icons/flat/crab.svg',
      displayOrder: 29,
      tags: ['crab', 'cua'],
    ),
    ProductIcon(
      id: 'cracker',
      name: 'Cracker',
      nameVi: 'Cracker',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/cracker.svg',
      displayOrder: 30,
      tags: ['cracker', 'cracker'],
    ),
    ProductIcon(
      id: 'cream',
      name: 'Cream',
      nameVi: 'Kem',
      category: 'dairy',
      tier: IconTier.free,
      emoji: '🍨',
      assetPath: 'assets/product_icons/flat/cream.svg',
      displayOrder: 31,
      tags: ['cream', 'kem'],
    ),
    ProductIcon(
      id: 'croissant',
      name: 'Croissant',
      nameVi: 'Croissant',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/croissant.svg',
      displayOrder: 32,
      tags: ['croissant', 'croissant'],
    ),
    ProductIcon(
      id: 'cucumber',
      name: 'Cucumber',
      nameVi: 'Dưa chuột',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🥒',
      assetPath: 'assets/product_icons/flat/cucumber.svg',
      displayOrder: 33,
      tags: ['cucumber', 'dưa chuột'],
    ),
    ProductIcon(
      id: 'egg',
      name: 'Egg',
      nameVi: 'Trứng',
      category: 'eggs',
      tier: IconTier.free,
      emoji: '🥚',
      assetPath: 'assets/product_icons/flat/egg.svg',
      displayOrder: 34,
      tags: ['egg', 'trứng'],
    ),
    ProductIcon(
      id: 'eggplant',
      name: 'Eggplant',
      nameVi: 'Cà tím',
      category: 'eggs',
      tier: IconTier.free,
      emoji: '🍆',
      assetPath: 'assets/product_icons/flat/eggplant.svg',
      displayOrder: 35,
      tags: ['eggplant', 'cà tím'],
    ),
    ProductIcon(
      id: 'fish',
      name: 'Fish',
      nameVi: 'Cá',
      category: 'other',
      tier: IconTier.free,
      emoji: '🐟',
      assetPath: 'assets/product_icons/flat/fish.svg',
      displayOrder: 36,
      tags: ['fish', 'cá'],
    ),
    ProductIcon(
      id: 'fried_egg',
      name: 'Fried Egg',
      nameVi: 'Fried Egg',
      category: 'eggs',
      tier: IconTier.free,
      emoji: '🥚',
      assetPath: 'assets/product_icons/flat/fried_egg.svg',
      displayOrder: 37,
      tags: ['fried egg', 'fried egg'],
    ),
    ProductIcon(
      id: 'garlic',
      name: 'Garlic',
      nameVi: 'Tỏi',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/garlic.svg',
      displayOrder: 38,
      tags: ['garlic', 'tỏi'],
    ),
    ProductIcon(
      id: 'ginger',
      name: 'Ginger',
      nameVi: 'Gừng',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/ginger.svg',
      displayOrder: 39,
      tags: ['ginger', 'gừng'],
    ),
    ProductIcon(
      id: 'grapes',
      name: 'Grapes',
      nameVi: 'Nho',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍇',
      assetPath: 'assets/product_icons/flat/grapes.svg',
      displayOrder: 40,
      tags: ['grapes', 'nho'],
    ),
    ProductIcon(
      id: 'ham',
      name: 'Ham',
      nameVi: 'Giăm bông',
      category: 'meat',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/ham.svg',
      displayOrder: 41,
      tags: ['ham', 'giăm bông'],
    ),
    ProductIcon(
      id: 'honey',
      name: 'Honey',
      nameVi: 'Honey',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/honey.svg',
      displayOrder: 42,
      tags: ['honey', 'honey'],
    ),
    ProductIcon(
      id: 'hot_pepper',
      name: 'Hot Pepper',
      nameVi: 'Hot Pepper',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/hot_pepper.svg',
      displayOrder: 43,
      tags: ['hot pepper', 'hot pepper'],
    ),
    ProductIcon(
      id: 'ice_cream',
      name: 'Ice Cream',
      nameVi: 'Kem',
      category: 'dairy',
      tier: IconTier.free,
      emoji: '🍨',
      assetPath: 'assets/product_icons/flat/ice_cream.svg',
      displayOrder: 44,
      tags: ['ice cream', 'kem'],
    ),
    ProductIcon(
      id: 'kiwi',
      name: 'Kiwi',
      nameVi: 'Kiwi',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🥝',
      assetPath: 'assets/product_icons/flat/kiwi.svg',
      displayOrder: 45,
      tags: ['kiwi', 'kiwi'],
    ),
    ProductIcon(
      id: 'leafy_green',
      name: 'Leafy Green',
      nameVi: 'Leafy Green',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/leafy_green.svg',
      displayOrder: 46,
      tags: ['leafy green', 'leafy green'],
    ),
    ProductIcon(
      id: 'lemon',
      name: 'Lemon',
      nameVi: 'Chanh',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍋',
      assetPath: 'assets/product_icons/flat/lemon.svg',
      displayOrder: 47,
      tags: ['lemon', 'chanh'],
    ),
    ProductIcon(
      id: 'lettuce',
      name: 'Lettuce',
      nameVi: 'Rau xà lách',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/lettuce.svg',
      displayOrder: 48,
      tags: ['lettuce', 'rau xà lách'],
    ),
    ProductIcon(
      id: 'lobster',
      name: 'Lobster',
      nameVi: 'Lobster',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/lobster.svg',
      displayOrder: 49,
      tags: ['lobster', 'lobster'],
    ),
    ProductIcon(
      id: 'mango',
      name: 'Mango',
      nameVi: 'Xoài',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🥭',
      assetPath: 'assets/product_icons/flat/mango.svg',
      displayOrder: 50,
      tags: ['mango', 'xoài'],
    ),
    ProductIcon(
      id: 'meat',
      name: 'Meat',
      nameVi: 'Meat',
      category: 'meat',
      tier: IconTier.free,
      emoji: '🥩',
      assetPath: 'assets/product_icons/flat/meat.svg',
      displayOrder: 51,
      tags: ['meat', 'meat'],
    ),
    ProductIcon(
      id: 'melon',
      name: 'Melon',
      nameVi: 'Dưa lưới',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍉',
      assetPath: 'assets/product_icons/flat/melon.svg',
      displayOrder: 52,
      tags: ['melon', 'dưa lưới'],
    ),
    ProductIcon(
      id: 'milk',
      name: 'Milk',
      nameVi: 'Sữa',
      category: 'dairy',
      tier: IconTier.free,
      emoji: '🥛',
      assetPath: 'assets/product_icons/flat/milk.svg',
      displayOrder: 53,
      tags: ['milk', 'sữa'],
    ),
    ProductIcon(
      id: 'mushroom',
      name: 'Mushroom',
      nameVi: 'Nấm',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🍄',
      assetPath: 'assets/product_icons/flat/mushroom.svg',
      displayOrder: 54,
      tags: ['mushroom', 'nấm'],
    ),
    ProductIcon(
      id: 'noodles',
      name: 'Noodles',
      nameVi: 'Mì',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/noodles.svg',
      displayOrder: 55,
      tags: ['noodles', 'mì'],
    ),
    ProductIcon(
      id: 'olive',
      name: 'Olive',
      nameVi: 'Olive',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/olive.svg',
      displayOrder: 56,
      tags: ['olive', 'olive'],
    ),
    ProductIcon(
      id: 'onion',
      name: 'Onion',
      nameVi: 'Hành tây',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/onion.svg',
      displayOrder: 57,
      tags: ['onion', 'hành tây'],
    ),
    ProductIcon(
      id: 'orange',
      name: 'Orange',
      nameVi: 'Cam',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍊',
      assetPath: 'assets/product_icons/flat/orange.svg',
      displayOrder: 58,
      tags: ['orange', 'cam'],
    ),
    ProductIcon(
      id: 'oyster',
      name: 'Oyster',
      nameVi: 'Oyster',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/oyster.svg',
      displayOrder: 59,
      tags: ['oyster', 'oyster'],
    ),
    ProductIcon(
      id: 'papaya',
      name: 'Papaya',
      nameVi: 'Đu đủ',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/papaya.svg',
      displayOrder: 60,
      tags: ['papaya', 'đu đủ'],
    ),
    ProductIcon(
      id: 'peach',
      name: 'Peach',
      nameVi: 'Đào',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍑',
      assetPath: 'assets/product_icons/flat/peach.svg',
      displayOrder: 61,
      tags: ['peach', 'đào'],
    ),
    ProductIcon(
      id: 'peanuts',
      name: 'Peanuts',
      nameVi: 'Đậu phộng',
      category: 'dry_food',
      tier: IconTier.free,
      emoji: '🥜',
      assetPath: 'assets/product_icons/flat/peanuts.svg',
      displayOrder: 62,
      tags: ['peanuts', 'đậu phộng'],
    ),
    ProductIcon(
      id: 'pear',
      name: 'Pear',
      nameVi: 'Lê',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍐',
      assetPath: 'assets/product_icons/flat/pear.svg',
      displayOrder: 63,
      tags: ['pear', 'lê'],
    ),
    ProductIcon(
      id: 'pepper_hot',
      name: 'Pepper Hot',
      nameVi: 'Pepper Hot',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/pepper_hot.svg',
      displayOrder: 64,
      tags: ['pepper hot', 'pepper hot'],
    ),
    ProductIcon(
      id: 'pineapple',
      name: 'Pineapple',
      nameVi: 'Dứa',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍍',
      assetPath: 'assets/product_icons/flat/pineapple.svg',
      displayOrder: 65,
      tags: ['pineapple', 'dứa'],
    ),
    ProductIcon(
      id: 'popcorn',
      name: 'Popcorn',
      nameVi: 'Popcorn',
      category: 'other',
      tier: IconTier.free,
      emoji: '🌽',
      assetPath: 'assets/product_icons/flat/popcorn.svg',
      displayOrder: 66,
      tags: ['popcorn', 'popcorn'],
    ),
    ProductIcon(
      id: 'pork',
      name: 'Pork',
      nameVi: 'Thịt heo',
      category: 'meat',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/pork.svg',
      displayOrder: 67,
      tags: ['pork', 'thịt heo'],
    ),
    ProductIcon(
      id: 'potato',
      name: 'Potato',
      nameVi: 'Khoai tây',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/potato.svg',
      displayOrder: 68,
      tags: ['potato', 'khoai tây'],
    ),
    ProductIcon(
      id: 'poultry_leg',
      name: 'Poultry Leg',
      nameVi: 'Poultry Leg',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/poultry_leg.svg',
      displayOrder: 69,
      tags: ['poultry leg', 'poultry leg'],
    ),
    ProductIcon(
      id: 'pretzel',
      name: 'Pretzel',
      nameVi: 'Pretzel',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/pretzel.svg',
      displayOrder: 70,
      tags: ['pretzel', 'pretzel'],
    ),
    ProductIcon(
      id: 'pumpkin',
      name: 'Pumpkin',
      nameVi: 'Bí đỏ',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/pumpkin.svg',
      displayOrder: 71,
      tags: ['pumpkin', 'bí đỏ'],
    ),
    ProductIcon(
      id: 'rice',
      name: 'Rice',
      nameVi: 'Gạo',
      category: 'frozen',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/rice.svg',
      displayOrder: 72,
      tags: ['rice', 'gạo'],
    ),
    ProductIcon(
      id: 'rice_ball',
      name: 'Rice Ball',
      nameVi: 'Rice Ball',
      category: 'frozen',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/rice_ball.svg',
      displayOrder: 73,
      tags: ['rice ball', 'rice ball'],
    ),
    ProductIcon(
      id: 'rice_cracker',
      name: 'Rice Cracker',
      nameVi: 'Rice Cracker',
      category: 'frozen',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/rice_cracker.svg',
      displayOrder: 74,
      tags: ['rice cracker', 'rice cracker'],
    ),
    ProductIcon(
      id: 'salt',
      name: 'Salt',
      nameVi: 'Muối',
      category: 'condiments',
      tier: IconTier.free,
      emoji: '🧂',
      assetPath: 'assets/product_icons/flat/salt.svg',
      displayOrder: 75,
      tags: ['salt', 'muối'],
    ),
    ProductIcon(
      id: 'sausage',
      name: 'Sausage',
      nameVi: 'Xúc xích',
      category: 'meat',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/sausage.svg',
      displayOrder: 76,
      tags: ['sausage', 'xúc xích'],
    ),
    ProductIcon(
      id: 'shrimp',
      name: 'Shrimp',
      nameVi: 'Tôm',
      category: 'other',
      tier: IconTier.free,
      emoji: '🦐',
      assetPath: 'assets/product_icons/flat/shrimp.svg',
      displayOrder: 77,
      tags: ['shrimp', 'tôm'],
    ),
    ProductIcon(
      id: 'spaghetti',
      name: 'Spaghetti',
      nameVi: 'Spaghetti',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/spaghetti.svg',
      displayOrder: 78,
      tags: ['spaghetti', 'spaghetti'],
    ),
    ProductIcon(
      id: 'squid',
      name: 'Squid',
      nameVi: 'Mực',
      category: 'other',
      tier: IconTier.free,
      emoji: '🦑',
      assetPath: 'assets/product_icons/flat/squid.svg',
      displayOrder: 79,
      tags: ['squid', 'mực'],
    ),
    ProductIcon(
      id: 'strawberry',
      name: 'Strawberry',
      nameVi: 'Dâu tây',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍓',
      assetPath: 'assets/product_icons/flat/strawberry.svg',
      displayOrder: 80,
      tags: ['strawberry', 'dâu tây'],
    ),
    ProductIcon(
      id: 'tangerine',
      name: 'Tangerine',
      nameVi: 'Quýt',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/tangerine.svg',
      displayOrder: 81,
      tags: ['tangerine', 'quýt'],
    ),
    ProductIcon(
      id: 'tomato',
      name: 'Tomato',
      nameVi: 'Cà chua',
      category: 'vegetables',
      tier: IconTier.free,
      emoji: '🍅',
      assetPath: 'assets/product_icons/flat/tomato.svg',
      displayOrder: 82,
      tags: ['tomato', 'cà chua'],
    ),
    ProductIcon(
      id: 'turkey',
      name: 'Turkey',
      nameVi: 'Turkey',
      category: 'other',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/turkey.svg',
      displayOrder: 83,
      tags: ['turkey', 'turkey'],
    ),
    ProductIcon(
      id: 'watermelon',
      name: 'Watermelon',
      nameVi: 'Dưa hấu',
      category: 'fruits',
      tier: IconTier.free,
      emoji: '🍉',
      assetPath: 'assets/product_icons/flat/watermelon.svg',
      displayOrder: 84,
      tags: ['watermelon', 'dưa hấu'],
    ),
    ProductIcon(
      id: 'yogurt',
      name: 'Yogurt',
      nameVi: 'Sữa chua',
      category: 'dairy',
      tier: IconTier.free,
      emoji: '📦',
      assetPath: 'assets/product_icons/flat/yogurt.svg',
      displayOrder: 85,
      tags: ['yogurt', 'sữa chua'],
    ),
  ];

  // ============================================================================
  // PREMIUM ICONS - VIP members only (3D/PNG style)
  // ============================================================================

  static const List<ProductIcon> premiumIcons = [
    ProductIcon(
      id: 'apple_green',
      name: 'Apple Green',
      nameVi: 'Táo xanh',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '🍎',
      assetPath: 'assets/product_icons/3d/apple_green.png',
      displayOrder: 1,
      tags: ['apple green', 'táo xanh'],
    ),
    ProductIcon(
      id: 'apple_red',
      name: 'Apple Red',
      nameVi: 'Táo đỏ',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '🍎',
      assetPath: 'assets/product_icons/3d/apple_red.png',
      displayOrder: 2,
      tags: ['apple red', 'táo đỏ'],
    ),
    ProductIcon(
      id: 'avocado',
      name: 'Avocado',
      nameVi: 'Avocado',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/avocado.png',
      displayOrder: 3,
      tags: ['avocado', 'avocado'],
    ),
    ProductIcon(
      id: 'bacon',
      name: 'Bacon',
      nameVi: 'Thịt xông khói',
      category: 'meat',
      tier: IconTier.premium,
      emoji: '🥓',
      assetPath: 'assets/product_icons/3d/bacon.png',
      displayOrder: 4,
      tags: ['bacon', 'thịt xông khói'],
    ),
    ProductIcon(
      id: 'bagel',
      name: 'Bagel',
      nameVi: 'Bagel',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/bagel.png',
      displayOrder: 5,
      tags: ['bagel', 'bagel'],
    ),
    ProductIcon(
      id: 'baguette',
      name: 'Baguette',
      nameVi: 'Baguette',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/baguette.png',
      displayOrder: 6,
      tags: ['baguette', 'baguette'],
    ),
    ProductIcon(
      id: 'banana',
      name: 'Banana',
      nameVi: 'Chuối',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '🍌',
      assetPath: 'assets/product_icons/3d/banana.png',
      displayOrder: 7,
      tags: ['banana', 'chuối'],
    ),
    ProductIcon(
      id: 'beans',
      name: 'Beans',
      nameVi: 'Đậu',
      category: 'dry_food',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/beans.png',
      displayOrder: 8,
      tags: ['beans', 'đậu'],
    ),
    ProductIcon(
      id: 'beef',
      name: 'Beef',
      nameVi: 'Thịt bò',
      category: 'meat',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/beef.png',
      displayOrder: 9,
      tags: ['beef', 'thịt bò'],
    ),
    ProductIcon(
      id: 'bell_pepper',
      name: 'Bell Pepper',
      nameVi: 'Ớt chuông',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/bell_pepper.png',
      displayOrder: 10,
      tags: ['bell pepper', 'ớt chuông'],
    ),
    ProductIcon(
      id: 'blueberries',
      name: 'Blueberries',
      nameVi: 'Việt quất',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/blueberries.png',
      displayOrder: 11,
      tags: ['blueberries', 'việt quất'],
    ),
    ProductIcon(
      id: 'bottle',
      name: 'Bottle',
      nameVi: 'Bottle',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/bottle.png',
      displayOrder: 12,
      tags: ['bottle', 'bottle'],
    ),
    ProductIcon(
      id: 'bread',
      name: 'Bread',
      nameVi: 'Bánh mì',
      category: 'dry_food',
      tier: IconTier.premium,
      emoji: '🍞',
      assetPath: 'assets/product_icons/3d/bread.png',
      displayOrder: 13,
      tags: ['bread', 'bánh mì'],
    ),
    ProductIcon(
      id: 'broccoli',
      name: 'Broccoli',
      nameVi: 'Bông cải xanh',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '🥦',
      assetPath: 'assets/product_icons/3d/broccoli.png',
      displayOrder: 14,
      tags: ['broccoli', 'bông cải xanh'],
    ),
    ProductIcon(
      id: 'butter',
      name: 'Butter',
      nameVi: 'Bơ',
      category: 'dairy',
      tier: IconTier.premium,
      emoji: '🧈',
      assetPath: 'assets/product_icons/3d/butter.png',
      displayOrder: 15,
      tags: ['butter', 'bơ'],
    ),
    ProductIcon(
      id: 'cabbage',
      name: 'Cabbage',
      nameVi: 'Bắp cải',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/cabbage.png',
      displayOrder: 16,
      tags: ['cabbage', 'bắp cải'],
    ),
    ProductIcon(
      id: 'candy',
      name: 'Candy',
      nameVi: 'Candy',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/candy.png',
      displayOrder: 17,
      tags: ['candy', 'candy'],
    ),
    ProductIcon(
      id: 'carrot',
      name: 'Carrot',
      nameVi: 'Cà rốt',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '🥕',
      assetPath: 'assets/product_icons/3d/carrot.png',
      displayOrder: 18,
      tags: ['carrot', 'cà rốt'],
    ),
    ProductIcon(
      id: 'cauliflower',
      name: 'Cauliflower',
      nameVi: 'Bông cải trắng',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/cauliflower.png',
      displayOrder: 19,
      tags: ['cauliflower', 'bông cải trắng'],
    ),
    ProductIcon(
      id: 'cereal',
      name: 'Cereal',
      nameVi: 'Ngũ cốc',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/cereal.png',
      displayOrder: 20,
      tags: ['cereal', 'ngũ cốc'],
    ),
    ProductIcon(
      id: 'cheese',
      name: 'Cheese',
      nameVi: 'Phô mai',
      category: 'dairy',
      tier: IconTier.premium,
      emoji: '🧀',
      assetPath: 'assets/product_icons/3d/cheese.png',
      displayOrder: 21,
      tags: ['cheese', 'phô mai'],
    ),
    ProductIcon(
      id: 'cherries',
      name: 'Cherries',
      nameVi: 'Cherry',
      category: 'other',
      tier: IconTier.premium,
      emoji: '🍒',
      assetPath: 'assets/product_icons/3d/cherries.png',
      displayOrder: 22,
      tags: ['cherries', 'cherry'],
    ),
    ProductIcon(
      id: 'chestnut',
      name: 'Chestnut',
      nameVi: 'Chestnut',
      category: 'dry_food',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/chestnut.png',
      displayOrder: 23,
      tags: ['chestnut', 'chestnut'],
    ),
    ProductIcon(
      id: 'chicken',
      name: 'Chicken',
      nameVi: 'Thịt gà',
      category: 'meat',
      tier: IconTier.premium,
      emoji: '🍗',
      assetPath: 'assets/product_icons/3d/chicken.png',
      displayOrder: 24,
      tags: ['chicken', 'thịt gà'],
    ),
    ProductIcon(
      id: 'chocolate',
      name: 'Chocolate',
      nameVi: 'Chocolate',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/chocolate.png',
      displayOrder: 25,
      tags: ['chocolate', 'chocolate'],
    ),
    ProductIcon(
      id: 'coconut',
      name: 'Coconut',
      nameVi: 'Coconut',
      category: 'dry_food',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/coconut.png',
      displayOrder: 26,
      tags: ['coconut', 'coconut'],
    ),
    ProductIcon(
      id: 'cookie',
      name: 'Cookie',
      nameVi: 'Cookie',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/cookie.png',
      displayOrder: 27,
      tags: ['cookie', 'cookie'],
    ),
    ProductIcon(
      id: 'corn',
      name: 'Corn',
      nameVi: 'Ngô',
      category: 'other',
      tier: IconTier.premium,
      emoji: '🌽',
      assetPath: 'assets/product_icons/3d/corn.png',
      displayOrder: 28,
      tags: ['corn', 'ngô'],
    ),
    ProductIcon(
      id: 'crab',
      name: 'Crab',
      nameVi: 'Cua',
      category: 'other',
      tier: IconTier.premium,
      emoji: '🦀',
      assetPath: 'assets/product_icons/3d/crab.png',
      displayOrder: 29,
      tags: ['crab', 'cua'],
    ),
    ProductIcon(
      id: 'cracker',
      name: 'Cracker',
      nameVi: 'Cracker',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/cracker.png',
      displayOrder: 30,
      tags: ['cracker', 'cracker'],
    ),
    ProductIcon(
      id: 'cream',
      name: 'Cream',
      nameVi: 'Kem',
      category: 'dairy',
      tier: IconTier.premium,
      emoji: '🍨',
      assetPath: 'assets/product_icons/3d/cream.png',
      displayOrder: 31,
      tags: ['cream', 'kem'],
    ),
    ProductIcon(
      id: 'croissant',
      name: 'Croissant',
      nameVi: 'Croissant',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/croissant.png',
      displayOrder: 32,
      tags: ['croissant', 'croissant'],
    ),
    ProductIcon(
      id: 'cucumber',
      name: 'Cucumber',
      nameVi: 'Dưa chuột',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '🥒',
      assetPath: 'assets/product_icons/3d/cucumber.png',
      displayOrder: 33,
      tags: ['cucumber', 'dưa chuột'],
    ),
    ProductIcon(
      id: 'egg',
      name: 'Egg',
      nameVi: 'Trứng',
      category: 'eggs',
      tier: IconTier.premium,
      emoji: '🥚',
      assetPath: 'assets/product_icons/3d/egg.png',
      displayOrder: 34,
      tags: ['egg', 'trứng'],
    ),
    ProductIcon(
      id: 'eggplant',
      name: 'Eggplant',
      nameVi: 'Cà tím',
      category: 'eggs',
      tier: IconTier.premium,
      emoji: '🍆',
      assetPath: 'assets/product_icons/3d/eggplant.png',
      displayOrder: 35,
      tags: ['eggplant', 'cà tím'],
    ),
    ProductIcon(
      id: 'fish',
      name: 'Fish',
      nameVi: 'Cá',
      category: 'other',
      tier: IconTier.premium,
      emoji: '🐟',
      assetPath: 'assets/product_icons/3d/fish.png',
      displayOrder: 36,
      tags: ['fish', 'cá'],
    ),
    ProductIcon(
      id: 'fried_egg',
      name: 'Fried Egg',
      nameVi: 'Fried Egg',
      category: 'eggs',
      tier: IconTier.premium,
      emoji: '🥚',
      assetPath: 'assets/product_icons/3d/fried_egg.png',
      displayOrder: 37,
      tags: ['fried egg', 'fried egg'],
    ),
    ProductIcon(
      id: 'garlic',
      name: 'Garlic',
      nameVi: 'Tỏi',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/garlic.png',
      displayOrder: 38,
      tags: ['garlic', 'tỏi'],
    ),
    ProductIcon(
      id: 'ginger',
      name: 'Ginger',
      nameVi: 'Gừng',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/ginger.png',
      displayOrder: 39,
      tags: ['ginger', 'gừng'],
    ),
    ProductIcon(
      id: 'grapes',
      name: 'Grapes',
      nameVi: 'Nho',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '🍇',
      assetPath: 'assets/product_icons/3d/grapes.png',
      displayOrder: 40,
      tags: ['grapes', 'nho'],
    ),
    ProductIcon(
      id: 'ham',
      name: 'Ham',
      nameVi: 'Giăm bông',
      category: 'meat',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/ham.png',
      displayOrder: 41,
      tags: ['ham', 'giăm bông'],
    ),
    ProductIcon(
      id: 'honey',
      name: 'Honey',
      nameVi: 'Honey',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/honey.png',
      displayOrder: 42,
      tags: ['honey', 'honey'],
    ),
    ProductIcon(
      id: 'hot_pepper',
      name: 'Hot Pepper',
      nameVi: 'Hot Pepper',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/hot_pepper.png',
      displayOrder: 43,
      tags: ['hot pepper', 'hot pepper'],
    ),
    ProductIcon(
      id: 'ice_cream',
      name: 'Ice Cream',
      nameVi: 'Kem',
      category: 'dairy',
      tier: IconTier.premium,
      emoji: '🍨',
      assetPath: 'assets/product_icons/3d/ice_cream.png',
      displayOrder: 44,
      tags: ['ice cream', 'kem'],
    ),
    ProductIcon(
      id: 'kiwi',
      name: 'Kiwi',
      nameVi: 'Kiwi',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '🥝',
      assetPath: 'assets/product_icons/3d/kiwi.png',
      displayOrder: 45,
      tags: ['kiwi', 'kiwi'],
    ),
    ProductIcon(
      id: 'leafy_green',
      name: 'Leafy Green',
      nameVi: 'Leafy Green',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/leafy_green.png',
      displayOrder: 46,
      tags: ['leafy green', 'leafy green'],
    ),
    ProductIcon(
      id: 'lemon',
      name: 'Lemon',
      nameVi: 'Chanh',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '🍋',
      assetPath: 'assets/product_icons/3d/lemon.png',
      displayOrder: 47,
      tags: ['lemon', 'chanh'],
    ),
    ProductIcon(
      id: 'lettuce',
      name: 'Lettuce',
      nameVi: 'Rau xà lách',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/lettuce.png',
      displayOrder: 48,
      tags: ['lettuce', 'rau xà lách'],
    ),
    ProductIcon(
      id: 'lobster',
      name: 'Lobster',
      nameVi: 'Lobster',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/lobster.png',
      displayOrder: 49,
      tags: ['lobster', 'lobster'],
    ),
    ProductIcon(
      id: 'mango',
      name: 'Mango',
      nameVi: 'Xoài',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '🥭',
      assetPath: 'assets/product_icons/3d/mango.png',
      displayOrder: 50,
      tags: ['mango', 'xoài'],
    ),
    ProductIcon(
      id: 'meat',
      name: 'Meat',
      nameVi: 'Meat',
      category: 'meat',
      tier: IconTier.premium,
      emoji: '🥩',
      assetPath: 'assets/product_icons/3d/meat.png',
      displayOrder: 51,
      tags: ['meat', 'meat'],
    ),
    ProductIcon(
      id: 'melon',
      name: 'Melon',
      nameVi: 'Dưa lưới',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '🍉',
      assetPath: 'assets/product_icons/3d/melon.png',
      displayOrder: 52,
      tags: ['melon', 'dưa lưới'],
    ),
    ProductIcon(
      id: 'milk',
      name: 'Milk',
      nameVi: 'Sữa',
      category: 'dairy',
      tier: IconTier.premium,
      emoji: '🥛',
      assetPath: 'assets/product_icons/3d/milk.png',
      displayOrder: 53,
      tags: ['milk', 'sữa'],
    ),
    ProductIcon(
      id: 'mushroom',
      name: 'Mushroom',
      nameVi: 'Nấm',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '🍄',
      assetPath: 'assets/product_icons/3d/mushroom.png',
      displayOrder: 54,
      tags: ['mushroom', 'nấm'],
    ),
    ProductIcon(
      id: 'noodles',
      name: 'Noodles',
      nameVi: 'Mì',
      category: 'dry_food',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/noodles.png',
      displayOrder: 55,
      tags: ['noodles', 'mì'],
    ),
    ProductIcon(
      id: 'olive',
      name: 'Olive',
      nameVi: 'Olive',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/olive.png',
      displayOrder: 56,
      tags: ['olive', 'olive'],
    ),
    ProductIcon(
      id: 'onion',
      name: 'Onion',
      nameVi: 'Hành tây',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/onion.png',
      displayOrder: 57,
      tags: ['onion', 'hành tây'],
    ),
    ProductIcon(
      id: 'orange',
      name: 'Orange',
      nameVi: 'Cam',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '🍊',
      assetPath: 'assets/product_icons/3d/orange.png',
      displayOrder: 58,
      tags: ['orange', 'cam'],
    ),
    ProductIcon(
      id: 'oyster',
      name: 'Oyster',
      nameVi: 'Oyster',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/oyster.png',
      displayOrder: 59,
      tags: ['oyster', 'oyster'],
    ),
    ProductIcon(
      id: 'papaya',
      name: 'Papaya',
      nameVi: 'Đu đủ',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/papaya.png',
      displayOrder: 60,
      tags: ['papaya', 'đu đủ'],
    ),
    ProductIcon(
      id: 'peach',
      name: 'Peach',
      nameVi: 'Đào',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '🍑',
      assetPath: 'assets/product_icons/3d/peach.png',
      displayOrder: 61,
      tags: ['peach', 'đào'],
    ),
    ProductIcon(
      id: 'peanuts',
      name: 'Peanuts',
      nameVi: 'Đậu phộng',
      category: 'dry_food',
      tier: IconTier.premium,
      emoji: '🥜',
      assetPath: 'assets/product_icons/3d/peanuts.png',
      displayOrder: 62,
      tags: ['peanuts', 'đậu phộng'],
    ),
    ProductIcon(
      id: 'pear',
      name: 'Pear',
      nameVi: 'Lê',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '🍐',
      assetPath: 'assets/product_icons/3d/pear.png',
      displayOrder: 63,
      tags: ['pear', 'lê'],
    ),
    ProductIcon(
      id: 'pepper_hot',
      name: 'Pepper Hot',
      nameVi: 'Pepper Hot',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/pepper_hot.png',
      displayOrder: 64,
      tags: ['pepper hot', 'pepper hot'],
    ),
    ProductIcon(
      id: 'pineapple',
      name: 'Pineapple',
      nameVi: 'Dứa',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '🍍',
      assetPath: 'assets/product_icons/3d/pineapple.png',
      displayOrder: 65,
      tags: ['pineapple', 'dứa'],
    ),
    ProductIcon(
      id: 'popcorn',
      name: 'Popcorn',
      nameVi: 'Popcorn',
      category: 'other',
      tier: IconTier.premium,
      emoji: '🌽',
      assetPath: 'assets/product_icons/3d/popcorn.png',
      displayOrder: 66,
      tags: ['popcorn', 'popcorn'],
    ),
    ProductIcon(
      id: 'pork',
      name: 'Pork',
      nameVi: 'Thịt heo',
      category: 'meat',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/pork.png',
      displayOrder: 67,
      tags: ['pork', 'thịt heo'],
    ),
    ProductIcon(
      id: 'potato',
      name: 'Potato',
      nameVi: 'Khoai tây',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/potato.png',
      displayOrder: 68,
      tags: ['potato', 'khoai tây'],
    ),
    ProductIcon(
      id: 'poultry_leg',
      name: 'Poultry Leg',
      nameVi: 'Poultry Leg',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/poultry_leg.png',
      displayOrder: 69,
      tags: ['poultry leg', 'poultry leg'],
    ),
    ProductIcon(
      id: 'pretzel',
      name: 'Pretzel',
      nameVi: 'Pretzel',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/pretzel.png',
      displayOrder: 70,
      tags: ['pretzel', 'pretzel'],
    ),
    ProductIcon(
      id: 'pumpkin',
      name: 'Pumpkin',
      nameVi: 'Bí đỏ',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/pumpkin.png',
      displayOrder: 71,
      tags: ['pumpkin', 'bí đỏ'],
    ),
    ProductIcon(
      id: 'rice',
      name: 'Rice',
      nameVi: 'Gạo',
      category: 'frozen',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/rice.png',
      displayOrder: 72,
      tags: ['rice', 'gạo'],
    ),
    ProductIcon(
      id: 'rice_ball',
      name: 'Rice Ball',
      nameVi: 'Rice Ball',
      category: 'frozen',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/rice_ball.png',
      displayOrder: 73,
      tags: ['rice ball', 'rice ball'],
    ),
    ProductIcon(
      id: 'rice_cracker',
      name: 'Rice Cracker',
      nameVi: 'Rice Cracker',
      category: 'frozen',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/rice_cracker.png',
      displayOrder: 74,
      tags: ['rice cracker', 'rice cracker'],
    ),
    ProductIcon(
      id: 'salt',
      name: 'Salt',
      nameVi: 'Muối',
      category: 'condiments',
      tier: IconTier.premium,
      emoji: '🧂',
      assetPath: 'assets/product_icons/3d/salt.png',
      displayOrder: 75,
      tags: ['salt', 'muối'],
    ),
    ProductIcon(
      id: 'sausage',
      name: 'Sausage',
      nameVi: 'Xúc xích',
      category: 'meat',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/sausage.png',
      displayOrder: 76,
      tags: ['sausage', 'xúc xích'],
    ),
    ProductIcon(
      id: 'shrimp',
      name: 'Shrimp',
      nameVi: 'Tôm',
      category: 'other',
      tier: IconTier.premium,
      emoji: '🦐',
      assetPath: 'assets/product_icons/3d/shrimp.png',
      displayOrder: 77,
      tags: ['shrimp', 'tôm'],
    ),
    ProductIcon(
      id: 'spaghetti',
      name: 'Spaghetti',
      nameVi: 'Spaghetti',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/spaghetti.png',
      displayOrder: 78,
      tags: ['spaghetti', 'spaghetti'],
    ),
    ProductIcon(
      id: 'squid',
      name: 'Squid',
      nameVi: 'Mực',
      category: 'other',
      tier: IconTier.premium,
      emoji: '🦑',
      assetPath: 'assets/product_icons/3d/squid.png',
      displayOrder: 79,
      tags: ['squid', 'mực'],
    ),
    ProductIcon(
      id: 'strawberry',
      name: 'Strawberry',
      nameVi: 'Dâu tây',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '🍓',
      assetPath: 'assets/product_icons/3d/strawberry.png',
      displayOrder: 80,
      tags: ['strawberry', 'dâu tây'],
    ),
    ProductIcon(
      id: 'tangerine',
      name: 'Tangerine',
      nameVi: 'Quýt',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/tangerine.png',
      displayOrder: 81,
      tags: ['tangerine', 'quýt'],
    ),
    ProductIcon(
      id: 'tomato',
      name: 'Tomato',
      nameVi: 'Cà chua',
      category: 'vegetables',
      tier: IconTier.premium,
      emoji: '🍅',
      assetPath: 'assets/product_icons/3d/tomato.png',
      displayOrder: 82,
      tags: ['tomato', 'cà chua'],
    ),
    ProductIcon(
      id: 'turkey',
      name: 'Turkey',
      nameVi: 'Turkey',
      category: 'other',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/turkey.png',
      displayOrder: 83,
      tags: ['turkey', 'turkey'],
    ),
    ProductIcon(
      id: 'watermelon',
      name: 'Watermelon',
      nameVi: 'Dưa hấu',
      category: 'fruits',
      tier: IconTier.premium,
      emoji: '🍉',
      assetPath: 'assets/product_icons/3d/watermelon.png',
      displayOrder: 84,
      tags: ['watermelon', 'dưa hấu'],
    ),
    ProductIcon(
      id: 'yogurt',
      name: 'Yogurt',
      nameVi: 'Sữa chua',
      category: 'dairy',
      tier: IconTier.premium,
      emoji: '📦',
      assetPath: 'assets/product_icons/3d/yogurt.png',
      displayOrder: 85,
      tags: ['yogurt', 'sữa chua'],
    ),
  ];

  // Helper methods
  static List<ProductIcon> get allIcons => [...freeIcons, ...premiumIcons];

  static ProductIcon? getIconById(String? id) {
    if (id == null) return null;
    try {
      return allIcons.firstWhere((icon) => icon.id == id);
    } catch (e) {
      return null;
    }
  }

  static List<ProductIcon> getIconsByCategory(String category, {bool premiumOnly = false}) {
    final icons = premiumOnly ? premiumIcons : allIcons;
    return icons.where((icon) => icon.category == category).toList();
  }

  static List<ProductIcon> searchIcons(String query, {bool isVietnamese = false}) {
    final lowerQuery = query.toLowerCase();
    return allIcons.where((icon) => icon.matchesSearch(lowerQuery, isVietnamese: isVietnamese)).toList();
  }

  static List<ProductIcon> get freeIconsByDisplayOrder {
    final icons = List<ProductIcon>.from(freeIcons);
    icons.sort((a, b) => a.displayOrder.compareTo(b.displayOrder));
    return icons;
  }

  static List<ProductIcon> get premiumIconsByDisplayOrder {
    final icons = List<ProductIcon>.from(premiumIcons);
    icons.sort((a, b) => a.displayOrder.compareTo(b.displayOrder));
    return icons;
  }
}
